export const CHAT_SET_CONFIG = 'CHAT_SET_CONFIG';
export const CHAT_SET_APISERVER = 'CHAT_SET_APISERVER';
export const CHAT_SET_OPERATOR = 'CHAT_SET_OPERATOR';
export const CHAT_SET_ACTIVE = 'CHAT_SET_ACTIVE';
export const CHAT_TOGGLE_OPEN = 'CHAT_TOGGLE_OPEN';
export const OPERATOR_SET_FILTER = 'OPERATOR_SET_FILTER';
