export const CHAT_SET_CONFIG = 'CHAT_SET_CONFIG';
export const CHAT_SET_APISERVER = 'CHAT_SET_APISERVER';
export const CHAT_SET_OPERATOR = 'CHAT_SET_OPERATOR';
export const CHAT_SET_ACTIVE = 'CHAT_SET_ACTIVE';
export const CHAT_TOGGLE_OPEN = 'CHAT_TOGGLE_OPEN';
export const OPERATOR_SET_FILTER = 'OPERATOR_SET_FILTER';
export const CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE';

// Network Constants:
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAILURE = 'LOAD_MESSAGES_FAILURE';

// socket constants
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
export const SOCKET_CONNECTION_TIMEOUT = 'SOCKET_CONNECTION_TIMEOUT';
export const SOCKET_RECONNECTING = 'SOCKET_RECONNECTING';
export const SOCKET_RECONNECTED = 'SOCKET_RECONNECTED';
export const SOCKET_RECONNECT_ERROR = 'SOCKET_RECONNECT_ERROR';
export const SOCKET_RECONNECT_FAILED = 'SOCKET_RECONNECT_FAILED';
export const SOCKET_RECONNECT_TIMEOUT = 'SOCKET_RECONNECT_TIMEOUT';
