export const CHAT_OPEN_CONVERSATION = 'CHAT_OPEN_CONVERSATION';
export const CHAT_TAG_CLIENT = 'CHAT_TAG_CLIENT';
export const CHAT_SET_APISERVER = 'CHAT_SET_APISERVER';
export const CHAT_SET_OPERATOR = 'CHAT_SET_OPERATOR';
